global using System.Threading.Tasks;
global using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
global using Microsoft.Extensions.DependencyInjection;
global using ServerMTA;
global using ServerMTA.Model;
global using Microsoft.AspNetCore.Components;
global using System.Linq;
global using Microsoft.JSInterop;
global using ServerMTA.Shared;